//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Admin_ID { get; set; }
        public string Admin_Firstname { get; set; }
        public string Admin_Lastname { get; set; }
        public string Admin_Username { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_Gender { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Phone { get; set; }
    }
}
