//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Working_Schedule = new HashSet<Working_Schedule>();
        }
    
        public int Doctor_ID { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_Gender { get; set; }
        public int AcademicTitle_ID { get; set; }
        public int MedicalSpecialty_ID { get; set; }
    
        public virtual Academic_Title Academic_Title { get; set; }
        public virtual Medical_Specialty Medical_Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Working_Schedule> Working_Schedule { get; set; }
    }
}
