//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Invoice_Detail
    {
        public int MedicalInvoice_ID { get; set; }
        public int MedicalSpecialty_ID { get; set; }
        public int WorkingSchedule_ID { get; set; }
        public string HealthInsuranceStatus { get; set; }
    
        public virtual Medical_Invoice Medical_Invoice { get; set; }
        public virtual Medical_Specialty Medical_Specialty { get; set; }
        public virtual Working_Schedule Working_Schedule { get; set; }
    }
}
