//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medical_Invoice()
        {
            this.Medical_Invoice_Detail = new HashSet<Medical_Invoice_Detail>();
        }
    
        public int MedicalInvoice_ID { get; set; }
        public int Patient_ID { get; set; }
        public Nullable<System.DateTime> MedicalInvoice_Date { get; set; }
        public Nullable<double> MedicalInvoice_Cost { get; set; }
        public int PaymentMethod_ID { get; set; }
        public string Invoice_Status { get; set; }
        public string Payment_Status { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Invoice_Detail> Medical_Invoice_Detail { get; set; }
        public virtual Payment_Method Payment_Method { get; set; }
    }
}
