//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediPlusEntities : DbContext
    {
        public MediPlusEntities()
            : base("name=MediPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academic_Title> Academic_Title { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Medical_Invoice> Medical_Invoice { get; set; }
        public virtual DbSet<Medical_Invoice_Detail> Medical_Invoice_Detail { get; set; }
        public virtual DbSet<Medical_Specialty> Medical_Specialty { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Working_Day> Working_Day { get; set; }
        public virtual DbSet<Working_Room> Working_Room { get; set; }
        public virtual DbSet<Working_Schedule> Working_Schedule { get; set; }
        public virtual DbSet<Working_Time> Working_Time { get; set; }
        public virtual DbSet<vDoctor> vDoctors { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<vInvoice> vInvoices { get; set; }
        public virtual DbSet<vAppointment> vAppointments { get; set; }
    }
}
