//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Medical_Invoice = new HashSet<Medical_Invoice>();
        }
    
        public int Patient_ID { get; set; }
        public string Patient_Firstname { get; set; }
        public string Patient_Lastname { get; set; }
        public string Patient_Username { get; set; }
        public string Patient_Password { get; set; }
        public Nullable<System.DateTime> Patient_DoB { get; set; }
        public string Patient_Gender { get; set; }
        public string Patient_Ethnic { get; set; }
        public string Patient_Nationality { get; set; }
        public string Patient_IDCardNumber { get; set; }
        public string Patient_Phone { get; set; }
        public string Patient_Email { get; set; }
        public string Patient_Address { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public string Patient_Occupation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Invoice> Medical_Invoice { get; set; }
    }
}
