//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Method
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment_Method()
        {
            this.Medical_Invoice = new HashSet<Medical_Invoice>();
        }
    
        public int PaymentMethod_ID { get; set; }
        public string PaymentMethod_Name { get; set; }
        public string PaymentMethod_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Invoice> Medical_Invoice { get; set; }
    }
}
