//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAppointment
    {
        public int MedicalInvoice_ID { get; set; }
        public int MedicalSpecialty_ID { get; set; }
        public string Patient_Username { get; set; }
        public string MedicalSpecialty_Name { get; set; }
        public string AcademicTitle_Code { get; set; }
        public string Doctor_Name { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public string WorkingDay_Period { get; set; }
        public string WoringTime_Period { get; set; }
        public string WorkingRoom_Number { get; set; }
        public Nullable<double> MedicalSpecialty_ServicePrice { get; set; }
    }
}
