//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDoctor
    {
        public int Doctor_ID { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_Gender { get; set; }
        public string AcademicTitle_Code { get; set; }
        public string MedicalSpecialty_Name { get; set; }
    }
}
