//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInvoice
    {
        public int MedicalInvoice_ID { get; set; }
        public int Patient_ID { get; set; }
        public string Patient_Firstname { get; set; }
        public string Patient_Lastname { get; set; }
        public Nullable<System.DateTime> MedicalInvoice_Date { get; set; }
        public Nullable<double> MedicalInvoice_Cost { get; set; }
        public string PaymentMethod_Name { get; set; }
        public string Invoice_Status { get; set; }
        public string Payment_Status { get; set; }
    }
}
