//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Working_Schedule()
        {
            this.Medical_Invoice_Detail = new HashSet<Medical_Invoice_Detail>();
        }
    
        public int WorkingSchedule_ID { get; set; }
        public int Doctor_ID { get; set; }
        public int WorkingTime_ID { get; set; }
        public int WorkingDay_ID { get; set; }
        public Nullable<int> WorkingRoom_ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string ThemeColor { get; set; }
        public Nullable<bool> IsFullDay { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Invoice_Detail> Medical_Invoice_Detail { get; set; }
        public virtual Working_Day Working_Day { get; set; }
        public virtual Working_Room Working_Room { get; set; }
        public virtual Working_Time Working_Time { get; set; }
    }
}
