//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working_Day
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Working_Day()
        {
            this.Working_Schedule = new HashSet<Working_Schedule>();
        }
    
        public int WorkingDay_ID { get; set; }
        public string WorkingDay_Period { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Working_Schedule> Working_Schedule { get; set; }
    }
}
